version: '2'

services:

    #fast-CGI processer manager
    php7.0:
        build: ./docker/php/php70
        image: php-fpm:7.0
        container_name: php70
        networks:
            vmms_network:
                ipv4_address: 172.20.0.70
        ports:
            - "9070:9070"
        volumes:
            - /var/www/web:/var/www/web
            - ./etc/php/php70/php-fpm.d:/usr/local/etc/php-fpm.d
        links:
            - mysql
        depends_on:
            - mysql
        restart: always
    
    #PHP5.6
    php5.6:
        build: ./docker/php/php56
        image: php-fpm:5.6
        container_name: php56
        networks:
            vmms_network:
                ipv4_address: 172.20.0.56
        ports:
            - "9056:9056"
        volumes:
            - /var/www/web:/var/www/web
            - ./etc/php/php56/php-fpm.d:/usr/local/etc/php-fpm.d
            # - ./logs/php:/var/log/php-fpm
        links:
            - mysql
        depends_on:
            - mysql
        restart: always

    #nginx web app
    nginx:
        build: ./docker/nginx
        image: nginx
        container_name: nginx
        networks:
            vmms_network:
                ipv4_address: 172.20.0.4
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #nginx conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            #- ./etc/nginx/snippets:/etc/nginx/snippets
            - /var/www/web:/var/www/etc
            - ./etc/nginx/letsencrypt/:/etc/letsencrypt/
            #- ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            #log    
            #- ./logs/nginx:/var/log/nginx
        links:
            - httpd
        restart: always

    #apache web server
    httpd:
        build: ./docker/httpd
        image: httpd
        container_name: httpd
        networks:
            vmms_network:
                ipv4_address: 172.20.0.5
        ports:
            - '6669:6669'
        volumes:
            #source app
            - /var/www/web:/var/www/web
            - ./etc/httpd/conf.d/web:/etc/httpd/conf.d/web
            #httpd conf
            #- ./etc/httpd/httpd.conf:/etc/httpd/conf/httpd.conf
            #- ./etc/httpd/extra/vhosts:/etc/httpd/conf/extra/vhosts
            #log    
            #- ./logs/httpd:/var/log/httpd    
            #- ./logs/php:/var/log/php-fpm  
        links:
            - php7.0
            # - php7.1
            - php5.6
        depends_on:
            - mysql
        restart: always

    #MySQL config
    mysql:
        #build: ./docker/mysql
        image: 'bitnami/mysql:latest'
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: db
            MYSQL_ROOT_HOST: 0.0.0.0 
       
        networks:
            vmms_network:
                ipv4_address: 172.20.0.3
        ports:
            - '3306:3306'
        volumes:
            #- ./etc/mysql:/root
            - ./var/lib/mysql:/bitnami
            - ./etc/bitnami/mysql/conf:/opt/bitnami/mysql/conf
            #- ./logs/mysql:/var/log/mysql
        restart: always

#volumes:
#  db-data:
#  www:

networks:
  vmms_network:
 
    ipam:
       config:
           - subnet: 172.20.0.0/16
